import { getNextReviewData } from './sm2';
import { sameFoldedText } from './typedAnswer';
import type { StudyLanguage } from './types';

/**
 * Verb conjugation practice — Munli's first built-from-scratch tool.
 *
 * **Vocabulary, used consistently everywhere below.** A **table** is one verb in
 * one tense (`prendre · présent`). Its **boxes** are the forms, one per person.
 * **One question** is one box: the app names verb, tense and person, and the
 * learner types the form.
 *
 * ⚠️ **The schedule belongs to the table, not the box** — the user's call, and
 * the decision the rest of this module is shaped by. Missing `nous` brings the
 * whole `prendre · présent` table back sooner, and the next question from it may
 * be any of its six boxes. The argument is not item count (120 tables against
 * 720 boxes; both are ordinary deck sizes) but **what counts as one fact**: a
 * regular verb's six forms follow one rule, so six schedules would be six copies
 * of one fact.
 *
 * The accepted cost is that SM-2 learns "your `prendre` présent is shaky", not
 * "your *nous* is shaky" — and `misses` below recovers most of it without a
 * second scheduler, by *asking* the weak box more often while the table keeps
 * one schedule.
 *
 * ⚠️ **Per-verb scheduling is a later move and must stay a branch rather than a
 * migration** — regular verbs as a table, irregular verbs per box. So nothing
 * here may assume a table's six boxes *share* a schedule as a matter of
 * definition: `ConjugationProgress` is keyed by item id, and an item id is built
 * by a function. Splitting it later means more ids, not a different shape.
 *
 * **The content is computed, not authored**, which is what makes conjugation the
 * right first tool: a verb list plus rules, finite and checkable. ⚠️ **Irregular
 * verbs are deliberately absent** — they are recalled content, and
 * `docs/packs/README.md` governs: the model is not a source. They arrive from a
 * citable reference with its licence checked, which is its own job.
 *
 * **Zero model calls.** Grading is `typedAnswer.ts`, which is already right for
 * this: it folds apostrophes (so `j'ai` typed on an iOS keyboard matches) and
 * deliberately does *not* fold diacritics, and for a conjugation table the
 * accent is the content.
 */

/** A grammatical person, labelled as the language itself labels it. */
export interface ConjugationPerson {
  id: string;
  /** `je`, `nous` — the language's own word, never translated. */
  label: string;
}

/** A tense, named as a learner of that language learns its name. */
export interface ConjugationTense {
  id: string;
  /** `présent`, `imparfait` — not translated, for the same reason. */
  label: string;
}

/**
 * A verb, and the rule class its forms are generated by.
 *
 * `group` is what the engine dispatches on. There is no `irregular` member: an
 * irregular verb is not a rule class, it is stored forms, and admitting one here
 * would invite generating them.
 */
export interface ConjugationVerb {
  id: string;
  infinitive: string;
  group: 'er' | 'ir' | 're';
}

/** Everything one language's conjugation practice is built from. */
export interface ConjugationSpec {
  language: StudyLanguage;
  persons: readonly ConjugationPerson[];
  tenses: readonly ConjugationTense[];
  verbs: readonly ConjugationVerb[];
  /**
   * The subject pronoun as it is written in front of a given form — `je` but
   * `j'aime`. Used only to *accept* an extra spelling of an answer, never to
   * reject one, so an imperfect rule here can cost nothing.
   */
  subjectFor: (person: ConjugationPerson, form: string) => string;
}

/** One verb in one tense: the unit that carries a schedule. */
export interface ConjugationTable {
  verbId: string;
  infinitive: string;
  tenseId: string;
  tenseLabel: string;
  /** Person id → the form. Ordered as `spec.persons` is. */
  forms: Record<string, string>;
}

/**
 * What is remembered about a table.
 *
 * The SM-2 fields are the same four every other scheduled thing in the app
 * carries, so `getNextReviewData` applies unchanged. `misses` is the extra, and
 * it is a tally rather than a scheduler: it decides *which box to ask*, never
 * *when to ask*.
 *
 * `nextReview` is an ISO string rather than a Date or a Firestore Timestamp.
 * This lives in a plain map on the user document and is read by two platforms;
 * a string means neither has to know how the other serialises a date.
 */
export interface ConjugationProgress {
  interval: number;
  ease: number;
  repetitions: number;
  /** ISO 8601. */
  nextReview: string;
  /** Person id → how many times this box has been missed. */
  misses: Record<string, number>;
}

/** Progress for every table the learner has touched, keyed by item id. */
export type ConjugationProgressMap = Record<string, ConjugationProgress>;

/**
 * The id a table's schedule is filed under.
 *
 * A function rather than a template literal at each call site, because per-verb
 * scheduling later means *more* ids of a different shape, and every producer and
 * consumer of one has to change together.
 */
export function conjugationItemId(language: StudyLanguage, verbId: string, tenseId: string): string {
  return `${language}:${verbId}:${tenseId}`;
}

/* ── French ──────────────────────────────────────────────────────────────── */

const FRENCH_PERSONS: readonly ConjugationPerson[] = [
  { id: 's1', label: 'je' },
  { id: 's2', label: 'tu' },
  { id: 's3', label: 'il/elle' },
  { id: 'p1', label: 'nous' },
  { id: 'p2', label: 'vous' },
  { id: 'p3', label: 'ils/elles' },
];

const FRENCH_TENSES: readonly ConjugationTense[] = [
  { id: 'present', label: 'présent' },
  { id: 'imparfait', label: 'imparfait' },
  { id: 'futur', label: 'futur simple' },
];

const PRESENT_ENDINGS: Record<ConjugationVerb['group'], string[]> = {
  er: ['e', 'es', 'e', 'ons', 'ez', 'ent'],
  ir: ['is', 'is', 'it', 'issons', 'issez', 'issent'],
  re: ['s', 's', '', 'ons', 'ez', 'ent'],
};

const IMPERFECT_ENDINGS = ['ais', 'ais', 'ait', 'ions', 'iez', 'aient'];
const FUTURE_ENDINGS = ['ai', 'as', 'a', 'ons', 'ez', 'ont'];

/**
 * The two spelling rules that keep a *regular* verb regular.
 *
 * `-cer` and `-ger` verbs are not irregular: they follow the ordinary endings
 * and adjust the spelling so the consonant keeps its sound before `a` and `o`.
 * `nous commençons` and `nous mangeons`, but `nous commencions` and `nous
 * mangions` — the adjustment is keyed on the *ending*, which is why it is
 * applied at concatenation rather than baked into a stem.
 */
function joinFrench(infinitive: string, stem: string, ending: string): string {
  const softening = ending.startsWith('a') || ending.startsWith('o');
  if (softening && infinitive.endsWith('cer')) return `${stem.slice(0, -1)}ç${ending}`;
  if (softening && infinitive.endsWith('ger')) return `${stem}e${ending}`;
  return stem + ending;
}

/** The stem the imperfect is built on — the present `nous` form without `-ons`. */
function frenchImperfectStem(verb: ConjugationVerb): string {
  const base = verb.infinitive.slice(0, -2);
  return verb.group === 'ir' ? `${base}iss` : base;
}

/** The base the future is built on: the infinitive, less a final `-e`. */
function frenchFutureBase(verb: ConjugationVerb): string {
  return verb.group === 're' ? verb.infinitive.slice(0, -1) : verb.infinitive;
}

function frenchForms(verb: ConjugationVerb, tenseId: string): string[] {
  const stem = verb.infinitive.slice(0, -2);
  switch (tenseId) {
    case 'present':
      return PRESENT_ENDINGS[verb.group].map(e => joinFrench(verb.infinitive, stem, e));
    case 'imparfait': {
      const imperfect = frenchImperfectStem(verb);
      return IMPERFECT_ENDINGS.map(e => joinFrench(verb.infinitive, imperfect, e));
    }
    case 'futur': {
      const base = frenchFutureBase(verb);
      // The future is built on the infinitive, whose own `e` already softens the
      // consonant — so `joinFrench` has nothing to do here, and calling it would
      // be a coincidence rather than a rule.
      return FUTURE_ENDINGS.map(e => base + e);
    }
    default:
      throw new Error(`Unknown tense: ${tenseId}`);
  }
}

/**
 * Regular French verbs, one rule class each.
 *
 * ⚠️ **Common, not frequency-ranked.** Calling this a frequency list would be a
 * sourcing claim with nothing behind it. It is a starting set of verbs that are
 * regular, and ordering it properly is part of the same job that brings in the
 * irregulars.
 */
const FRENCH_VERBS: readonly ConjugationVerb[] = [
  { id: 'parler', infinitive: 'parler', group: 'er' },
  { id: 'regarder', infinitive: 'regarder', group: 'er' },
  { id: 'travailler', infinitive: 'travailler', group: 'er' },
  { id: 'chercher', infinitive: 'chercher', group: 'er' },
  { id: 'donner', infinitive: 'donner', group: 'er' },
  { id: 'aimer', infinitive: 'aimer', group: 'er' },
  { id: 'ecouter', infinitive: 'écouter', group: 'er' },
  { id: 'habiter', infinitive: 'habiter', group: 'er' },
  { id: 'manger', infinitive: 'manger', group: 'er' },
  { id: 'commencer', infinitive: 'commencer', group: 'er' },
  { id: 'finir', infinitive: 'finir', group: 'ir' },
  { id: 'choisir', infinitive: 'choisir', group: 'ir' },
  { id: 'reussir', infinitive: 'réussir', group: 'ir' },
  { id: 'grandir', infinitive: 'grandir', group: 'ir' },
  { id: 'vendre', infinitive: 'vendre', group: 're' },
  { id: 'attendre', infinitive: 'attendre', group: 're' },
  { id: 'repondre', infinitive: 'répondre', group: 're' },
  { id: 'entendre', infinitive: 'entendre', group: 're' },
];

const FRENCH_VOWELS = 'aeiouéèêëàâîïôöûùü';

const FRENCH_SPEC: ConjugationSpec = {
  language: 'French',
  persons: FRENCH_PERSONS,
  tenses: FRENCH_TENSES,
  verbs: FRENCH_VERBS,
  subjectFor: (person, form) => {
    if (person.id !== 's1') return person.label;
    const first = form.charAt(0).toLowerCase();
    return FRENCH_VOWELS.includes(first) || first === 'h' ? "j'" : 'je';
  },
};

/**
 * The languages conjugation practice exists for.
 *
 * ⚠️ **French only, and that is an assumption rather than a decision** — it is
 * the ask that opened this. The tool is language-generic and a language is a
 * spec, so changing the answer is a dataset swap, not a redesign.
 */
const SPECS: readonly ConjugationSpec[] = [FRENCH_SPEC];

export function conjugationSpec(language: StudyLanguage): ConjugationSpec | undefined {
  return SPECS.find(spec => spec.language === language);
}

export function hasConjugation(language: StudyLanguage): boolean {
  return conjugationSpec(language) !== undefined;
}

/* ── Tables ──────────────────────────────────────────────────────────────── */

export function buildTable(spec: ConjugationSpec, verb: ConjugationVerb, tenseId: string): ConjugationTable {
  const tense = spec.tenses.find(t => t.id === tenseId);
  if (!tense) throw new Error(`Unknown tense: ${tenseId}`);
  const forms = frenchForms(verb, tenseId);
  return {
    verbId: verb.id,
    infinitive: verb.infinitive,
    tenseId,
    tenseLabel: tense.label,
    forms: Object.fromEntries(spec.persons.map((p, i) => [p.id, forms[i]])),
  };
}

/** Every table for the given tenses, in verb order. */
export function buildTables(spec: ConjugationSpec, tenseIds: readonly string[]): ConjugationTable[] {
  const tables: ConjugationTable[] = [];
  for (const tenseId of tenseIds) {
    for (const verb of spec.verbs) tables.push(buildTable(spec, verb, tenseId));
  }
  return tables;
}

/* ── Scheduling ──────────────────────────────────────────────────────────── */

/**
 * The tables due now, soonest first, with never-practised ones ahead of them.
 *
 * A table with no progress has never been asked, so it is due — the same rule
 * `isDue` applies to an untracked card direction.
 */
export function dueTables(
  spec: ConjugationSpec,
  tables: readonly ConjugationTable[],
  progress: ConjugationProgressMap,
  now: Date = new Date(),
): ConjugationTable[] {
  const due = tables.filter(table => {
    const state = progress[conjugationItemId(spec.language, table.verbId, table.tenseId)];
    return !state || new Date(state.nextReview) <= now;
  });
  return due.sort((a, b) => {
    const sa = progress[conjugationItemId(spec.language, a.verbId, a.tenseId)];
    const sb = progress[conjugationItemId(spec.language, b.verbId, b.tenseId)];
    if (!sa && !sb) return 0;
    if (!sa) return -1;
    if (!sb) return 1;
    return new Date(sa.nextReview).getTime() - new Date(sb.nextReview).getTime();
  });
}

/**
 * Which box to ask from a table.
 *
 * ⚠️ **This is where the per-table schedule pays its debt.** One schedule cannot
 * know that your `nous` specifically is weak, but the tally can, so the box with
 * the most misses is asked first. Ties fall to `tiebreak`, which the caller
 * supplies (`Math.random` in the app, a fixed value in tests) — a stable choice
 * would ask the same box forever and teach exactly one sixth of the table.
 */
export function pickPerson(
  spec: ConjugationSpec,
  progress: ConjugationProgress | undefined,
  tiebreak: () => number = Math.random,
): ConjugationPerson {
  const misses = progress?.misses ?? {};
  let worst = -1;
  for (const person of spec.persons) worst = Math.max(worst, misses[person.id] ?? 0);
  const candidates = worst > 0
    ? spec.persons.filter(p => (misses[p.id] ?? 0) === worst)
    : spec.persons;
  return candidates[Math.min(candidates.length - 1, Math.floor(tiebreak() * candidates.length))];
}

/** What a hinted answer is worth. A subset of the card ratings, by design. */
export type ConjugationVerdict = 'again' | 'hard' | 'good';

/** A table that has never been practised. */
export function freshProgress(now: Date = new Date()): ConjugationProgress {
  return { interval: 0, ease: 2.5, repetitions: 0, nextReview: now.toISOString(), misses: {} };
}

/**
 * What a rating does to a table.
 *
 * The SM-2 half is `getNextReviewData`, unchanged and shared with every card in
 * the app. The tally is the local part: a miss increments the box that was
 * asked, and a correct answer clears it rather than decrementing — a box you
 * have now produced is not "less wrong than before", it is answered, and
 * decrementing would keep asking it long after it was learned.
 */
export function rateTable(
  current: ConjugationProgress | undefined,
  personId: string,
  verdict: ConjugationVerdict,
): ConjugationProgress {
  const base = current ?? freshProgress();
  const next = getNextReviewData(
    { interval: base.interval, ease: base.ease, repetitions: base.repetitions },
    verdict,
  );
  // ⚠️ The tally follows the *verdict*, not whether the string matched. A form
  // assembled from both hints is `again`, and it has to count as a miss here
  // too, or the box that needed both hints would stop being offered.
  const misses = { ...base.misses };
  if (verdict === 'again') misses[personId] = (misses[personId] ?? 0) + 1;
  else delete misses[personId];
  return {
    interval: next.interval,
    ease: next.ease,
    repetitions: next.repetitions,
    nextReview: next.nextReview.toISOString(),
    misses,
  };
}

/* ── Answering ───────────────────────────────────────────────────────────── */

/**
 * Every spelling of a box that counts as right.
 *
 * The bare form is the answer. The form behind its subject pronoun is accepted
 * too, because a learner who has drilled `j'aime` as a unit is not wrong — and
 * accepting more spellings can only ever turn a false miss into a pass, never
 * the reverse.
 */
export function acceptedForms(spec: ConjugationSpec, table: ConjugationTable, personId: string): string[] {
  const person = spec.persons.find(p => p.id === personId);
  const form = table.forms[personId];
  if (!person || !form) return [];
  const subject = spec.subjectFor(person, form);
  return [form, subject.endsWith("'") ? `${subject}${form}` : `${subject} ${form}`];
}

/** Whether what was typed answers the box. Local, pure, no model. */
export function isCorrectForm(
  spec: ConjugationSpec,
  table: ConjugationTable,
  personId: string,
  typed: string,
): boolean {
  return acceptedForms(spec, table, personId).some(accepted => sameFoldedText(accepted, typed));
}

/* ── Hints ───────────────────────────────────────────────────────────────── */

/**
 * A way out of an empty box that costs something.
 *
 * `vision.md` refuses multiple choice because offering candidates does the
 * retrieval for the learner, and then admits that refusing it leaves whoever
 * cannot start with nothing to do but be wrong. The answer is a hint that
 * *costs*: the search space narrows and **the verdict falls with it**, which is
 * `hintedVerdict` below.
 *
 * Two tiers, both derived from the answer rather than authored: the stem, then
 * the ending. Taking both leaves the learner assembling the form, which is
 * still production.
 */
export function conjugationHints(table: ConjugationTable, personId: string): string[] {
  const form = table.forms[personId];
  if (!form) return [];
  const split = Math.max(1, Math.ceil(form.length / 2));
  return [`${form.slice(0, split)}…`, `…${form.slice(split)}`];
}

/**
 * The best verdict still available after taking `hintsTaken` hints.
 *
 * A correct answer with no hints is `good`; one hint makes it `hard`; two means
 * the form was assembled from both halves, which is not recall, so it lapses.
 * The schedule is told — that is the whole point of a hint that costs.
 */
export function hintedVerdict(hintsTaken: number, correct: boolean): ConjugationVerdict {
  if (!correct) return 'again';
  if (hintsTaken === 0) return 'good';
  if (hintsTaken === 1) return 'hard';
  return 'again';
}

/* ── Progress ────────────────────────────────────────────────────────────── */

/** How one tense is going. */
export interface ConjugationTenseSummary {
  tenseId: string;
  label: string;
  /** Tables with any history at all. */
  practised: number;
  /** Tables that exist for this tense. */
  total: number;
  due: number;
}

/** A box the learner keeps getting wrong, named in full. */
export interface ConjugationWeakBox {
  infinitive: string;
  tenseLabel: string;
  personLabel: string;
  form: string;
  misses: number;
}

export interface ConjugationSummary {
  practised: number;
  total: number;
  due: number;
  byTense: ConjugationTenseSummary[];
  /** Most-missed first. Empty when nothing has been missed. */
  weakest: ConjugationWeakBox[];
}

/**
 * What Munli's Progress tab shows for conjugation.
 *
 * ⚠️ **`weakest` is the one thing here that a card-shaped progress view could
 * not produce**, and it is the payoff for the per-box miss tally. The schedule
 * knows a table is shaky; only the tally knows it is your `nous` — so the
 * summary can say `prendre · nous · présent` rather than a percentage.
 *
 * Counting `practised` as "has any history" rather than "is learned" is
 * deliberate: a maturity threshold here would be a second, quieter answer to
 * the question `isCardMature` already answers for cards, and conjugation has no
 * equivalent agreed-upon interval yet.
 */
export function summarizeConjugation(
  spec: ConjugationSpec,
  progress: ConjugationProgressMap,
  limit = 5,
  now: Date = new Date(),
): ConjugationSummary {
  const byTense: ConjugationTenseSummary[] = [];
  const weakest: ConjugationWeakBox[] = [];
  let practised = 0;
  let total = 0;
  let due = 0;

  for (const tense of spec.tenses) {
    let tensePractised = 0;
    let tenseDue = 0;
    for (const verb of spec.verbs) {
      const state = progress[conjugationItemId(spec.language, verb.id, tense.id)];
      if (state) {
        tensePractised += 1;
        if (new Date(state.nextReview) <= now) tenseDue += 1;
        for (const [personId, misses] of Object.entries(state.misses)) {
          const person = spec.persons.find(p => p.id === personId);
          if (!person || misses <= 0) continue;
          weakest.push({
            infinitive: verb.infinitive,
            tenseLabel: tense.label,
            personLabel: person.label,
            form: buildTable(spec, verb, tense.id).forms[personId],
            misses,
          });
        }
      } else {
        // Never practised is also never scheduled, which `dueTables` reads as
        // due — the same rule an untracked card direction gets.
        tenseDue += 1;
      }
    }
    byTense.push({
      tenseId: tense.id,
      label: tense.label,
      practised: tensePractised,
      total: spec.verbs.length,
      due: tenseDue,
    });
    practised += tensePractised;
    total += spec.verbs.length;
    due += tenseDue;
  }

  weakest.sort((a, b) => b.misses - a.misses);
  return { practised, total, due, byTense, weakest: weakest.slice(0, limit) };
}

/* ── Sessions ────────────────────────────────────────────────────────────── */

/** One question: a table, and which of its boxes to ask. */
export interface ConjugationQuestion {
  table: ConjugationTable;
  personId: string;
}

export interface ConjugationQueueOptions {
  /**
   * Include tables that are not due yet.
   *
   * Off by default, which is what makes a session *end*. The first cut drew
   * from the whole set whenever nothing was due, so practice never finished and
   * the due count meant nothing once it hit zero. Over-practising is a
   * legitimate thing to want — it is just something the learner should ask for
   * on the start screen rather than something the draw does silently.
   */
  includeNotDue?: boolean;
}

/**
 * The questions a session will ask, fixed at the moment it starts.
 *
 * ⚠️ **One question per table, and the box is chosen here rather than when the
 * question is shown.** The table is the scheduled item, so asking it twice in
 * one sitting would be two questions about one fact. Choosing the box up front
 * also keeps every draw inside this function — the screen renders a queue it
 * was handed, so nothing random or stateful happens during render.
 *
 * ⚠️ **The queue is owned by the session from here on.** Ratings written while
 * it runs move the picker's counts and must not rebuild it under someone eight
 * questions in — the same rule `buildReviewQueue` follows, and the reason
 * `review.tsx` keeps `cards` out of its queue-building dependencies.
 *
 * A miss therefore does not put the table back into the session in progress. It
 * is due again immediately (`rateTable` sets `nextReview` to now for `again`),
 * so it returns in the *next* session — "a session ends when it said it would".
 */
export function buildConjugationQueue(
  spec: ConjugationSpec,
  tables: readonly ConjugationTable[],
  progress: ConjugationProgressMap,
  options: ConjugationQueueOptions = {},
  now: Date = new Date(),
  random: () => number = Math.random,
): ConjugationQuestion[] {
  const pool = options.includeNotDue ? [...tables] : dueTables(spec, tables, progress, now);
  const questions = pool.map(table => ({
    table,
    personId: pickPerson(
      spec,
      progress[conjugationItemId(spec.language, table.verbId, table.tenseId)],
      random,
    ).id,
  }));
  // Fisher–Yates, matching `reviewQueue`'s. Due order is verb order, and a
  // session that always opened on `parler` would drill the top of the list.
  for (let i = questions.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [questions[i], questions[j]] = [questions[j], questions[i]];
  }
  return questions;
}
